$(function () {
	$.currency.interface['en_US'] = {
		title: 'Currency Converter',
		from: 'From',
		to: 'To',
		convert: 'Convert',
		loading: 'Loading...',
		backBtn: 'New conversion',
		equals1: '=',
		equals2: '=',
		err: 'Server temporary unvailabe',
	},
	$.currency.isocode['en_US'] = {
		AED: 'Arab Emirates Dirham (AED)',
		AFN: 'Afghan Afghani (AFN)',
		ALL: 'Albanian Lek (ALL)',
		AMD: 'Armenian Dram (AMD)',
		ANG: 'Neth. Antillean Guilder (ANG)',
		AOA: 'Angolan Kwanza (AOA)',
		ARS: 'Argentine Peso (ARS)',
		AUD: 'Australian Dollar (A&#36;)',
		AWG: 'Aruban Florin (AWG)',
		AZN: 'Azerbaijani Manat (AZN)',
		BAM: 'Bosnia-Her. Convertible Mark (BAM)',
		BBD: 'Barbadian Dollar (BBD)',
		BDT: 'Bangladeshi Taka (BDT)',
		BGN: 'Bulgarian Lev (BGN)',
		BHD: 'Bahraini Dinar (BHD)',
		BIF: 'Burundian Franc (BIF)',
		BMD: 'Bermudan Dollar (BMD)',
		BND: 'Brunei Dollar (BND)',
		BOB: 'Bolivian Boliviano (BOB)',
		BRL: 'Brazilian Real (R$)',
		BSD: 'Bahamian Dollar (BSD)',
		BTN: 'Bhutanese Ngultrum (BTN)',
		BWP: 'Botswanan Pula (BWP)',
		BYR: 'Belarusian Ruble (BYR)',
		BZD: 'Belize Dollar (BZD)',
		CAD: 'Canadian Dollar (CA&#36;)',
		CDF: 'Congolese Franc (CDF)',
		CHF: 'Swiss Franc (CHF)',
		CLP: 'Chilean Peso (CLP)',
		CNY: 'Chinese Yuan (CN&#165;)',
		COP: 'Colombian Peso (COP)',
		CRC: 'Costa Rican Colón (CRC)',
		CUP: 'Cuban Peso (CUP)',
		CVE: 'Cape Verdean Escudo (CVE)',
		CZK: 'Czech Republic Koruna (CZK)',
		DEM: 'German Mark (DEM)',
		DJF: 'Djiboutian Franc (DJF)',
		DKK: 'Danish Krone (DKK)',
		DOP: 'Dominican Peso (DOP)',
		DZD: 'Algerian Dinar (DZD)',
		// EEK: 'Estonian Kroon (EEK)', // obsolete
		EGP: 'Egyptian Pound (EGP)',
		ERN: 'Eritrean Nakfa (ERN)',
		ETB: 'Ethiopian Birr (ETB)',
		EUR: 'Euro (&#128;)',
		FJD: 'Fijian Dollar (FJD)',
		// FIM: 'Finnish Markka (FIM)', // obsolete
		FKP: 'Falkland Islands Pound (FKP)',
		// FRF: 'French Franc (FRF)', // obsolete
		GBP: 'British Pound Sterling (&#8356;)',
		GEL: 'Georgian Lari (GEL)',
		GHS: 'Ghanaian Cedi (GHS)',
		GIP: 'Gibraltar Pound (GIP)',
		GMD: 'Gambian Dalasi (GMD)',
		GNF: 'Guinean Franc (GNF)',
		GTQ: 'Guatemalan Quetzal (GTQ)',
		GYD: 'Guyanaese Dollar (GYD)',
		HKD: 'Hong Kong Dollar (HK&#36;)',
		HNL: 'Honduran Lempira (HNL)',
		HRK: 'Croatian Kuna (HRK)',
		HUF: 'Hungarian Forint (HUF)',
		HTG: 'Haitian Gourde (HTG)',
		IDR: 'Indonesian Rupiah (IDR)',
		// IEP: 'Irish Pound (IEP)', // obsolete
		ILS: 'Israeli New Sheqel (&#8362;)',
		INR: 'Indian Rupee (Rs.)',
		IQD: 'Iraqi Dinar (IQD)',
		IRR: 'Iranian Rial (IRR)',
		ISK: 'Icelandic Króna (ISK)',
		// ITL: 'Italian Lira (ITL)', // obsolete
		JMD: 'Jamaican Dollar (JMD)',
		JOD: 'Jordanian Dinar (JOD)',
		JPY: 'Japanese Yen (&#165;)',
		KES: 'Kenyan Shilling (KES)',
		KGS: 'Kyrgystani Som (KGS)',
		KHR: 'Cambodian Riel (KHR)',
		KMF: 'Comorian Franc (KMF)',
		KPW: 'North Korean Won (KPW)',
		KRW: 'South Korean Won (&#8361;)',
		KWD: 'Kuwaiti Dinar (KWD)',
		KYD: 'Cayman Islands Dollar (KYD)',
		KZT: 'Kazakhstani Tenge (KZT)',
		LAK: 'Laotian Kip (LAK)',
		LBP: 'Lebanese Pound (LBP)',
		LKR: 'Sri Lankan Rupee (LKR)',
		LRD: 'Liberian Dollar (LRD)',
		LSL: 'Lesotho Loti (LSL)',
		LTL: 'Lithuanian Litas (LTL)',
		// LVL: 'Latvian Lats (LVL)', // obsolete
		LYD: 'Libyan Dinar (LYD)',
		MAD: 'Moroccan Dirham (MAD)',
		MDL: 'Moldovan Leu (MDL)',
		MGA: 'Malagasy Ariary (MGA)',
		MKD: 'Macedonian Denar (MKD)',
		MMK: 'Myanmar Kyat (MMK)',
		MNT: 'Mongolian Tugrik (MNT)',
		MOP: 'Macanese Pataca (MOP)',
		MRO: 'Mauritanian Ouguiya (MRO)',
		MUR: 'Mauritian Rupee (MUR)',
		MVR: 'Maldivian Rufiyaa (MVR)',
		MWK: 'Malawian Kwacha (MWK)',
		MXN: 'Mexican Peso (MX&#36;)',
		MYR: 'Malaysian Ringgit (MYR)',
		MZN: 'Mozambican Metical (MZN)',
		NAD: 'Namibian Dollar (NAD)',
		NGN: 'Nigerian Naira (NGN)',
		NIO: 'Nicaraguan Córdoba (NIO)',
		NOK: 'Norwegian Krone (NOK)',
		NPR: 'Nepalese Rupee (NPR)',
		NZD: 'New Zealand Dollar (NZ&#36;)',
		OMR: 'Omani Rial (OMR)',
		PAB: 'Panamanian Balboa (PAB)',
		PEN: 'Peruvian Nuevo Sol (PEN)',
		PGK: 'Papua New Guinean Kina (PGK)',
		PHP: 'Philippine Peso (Php)',
		PKR: 'Pakistani Rupee (PKR)',
		PLN: 'Polish Zloty (PLN)',
		PYG: 'Paraguayan Guarani (PYG)',
		QAR: 'Qatari Rial (QAR)',
		RON: 'Romanian Leu (RON)',
		RSD: 'Serbian Dinar (RSD)',
		RUB: 'Russian Ruble (RUB)',
		RWF: 'Rwandan Franc (RWF)',
		SAR: 'Saudi Riyal (SAR)',
		SBD: 'Solomon Islands Dollar (SBD)',
		SCR: 'Seychellois Rupee (SCR)',
		SDG: 'Sudanese Pound (SDG)',
		SEK: 'Swedish Krona (SEK)',
		SGD: 'Singapore Dollar (SGD)',
		SHP: 'Saint Helena Pound (SHP)',
		SLL: 'Sierra Leonean Leone (SLL)',
		SOS: 'Somali Shilling (SOS)',
		SRD: 'Surinamese Dollar (SRD)',
		STD: 'São Tomé and Príncipe Dobra (STD)',
		SVC: 'Salvadoran Colón (SVC)',
		SYP: 'Syrian Pound (SYP)',
		SZL: 'Swazi Lilangeni (SZL)',
		// SKK: 'Slovak Koruna (SKK)', // obsolete
		THB: 'Thai Baht (&#3647;)',
		TJS: 'Tajikistani Somoni (TJS)',
		TMT: 'Turkmenistani Manat (TMT)',
		TND: 'Tunisian Dinar (TND)',
		TOP: 'Tongan Paʻanga (TOP)',
		TRY: 'Turkish Lira (TRY)',
		TTD: 'Trinidad and Tobago Dollar (TTD)',
		TWD: 'New Taiwan Dollar (NT&#36;)',
		TZS: 'Tanzanian Shilling (TZS)',
		UAH: 'Ukrainian Hryvnia (UAH)',
		UGX: 'Ugandan Shilling (UGX)',
		USD: 'US Dollar (&#36;)',
		UYU: 'Uruguayan Peso (UYU)',
		UZS: 'Uzbekistan Som (UZS)',
		VEF: 'Venezuelan Bolívar (VEF)',
		VND: 'Vietnamese Dong (&#8363;)',
		VUV: 'Vanuatu Vatu (VUV)',
		WST: 'Samoan Tala (WST)',
		XOF: 'CFA Franc BCEAO (CFA)',
		XCD: 'East Caribbean Dollar (EC&#36;)',
		XDR: 'Special Drawing Rights (XDR)',
		XOF: 'CFA Franc BCEAO (CFA)',
		XPF: 'CFP Franc (CFPF)',
		YER: 'Yemeni Rial (YER)',
		ZAR: 'South African Rand (ZAR)',
		ZMK: 'Zambian Kwacha (ZMK)',
	}
});